### ISSUE TITLE
Fix containers inside body:

### ISSUE THREAD

**Issue by vikas-kmr1** [vickyrules/PhotoPlayground#4]
Fix the container inside the body and enhance  responsive design of the body.

**Comment by Coryyyy** [comment]
@vickyrules can you assign this issue to me?  thanks.

**Comment by vikas-kmr1** [comment]
@Coryyyy sure.

**Comment by Coryyyy** [comment]
@vickyrules Hi! Hope you're having a spooky and fun Halloween! I just wanted to bring to your attention the PR I submitted today. I understand if the festivities have kept you busy, but whenever you get a chance, could you please take a look? It's related to my homework so.... I'd appreciate any feedback you might have.

Thank you and enjoy the holiday!
